### ISSUE TITLE
Is this gem working?

### ISSUE THREAD

**Issue by lautarocastillo** [rodrigomageste/zoop-ruby#1]
Hi @rodrigomageste,
I would like to know if this gem is working and if the project is alive.
I'm very interested because Zoop has no official gem for ruby.
Many thanks!

**Comment by rodrigomageste** [comment]
Hi @lautarocastillo, this gem is working and the project is alive. :)
Feel free to use it, any questions just talk to me. 
I'm preparing a decent README for this gem.
